<div class="col-lg-8 mw">
    <div class="article">
        <h2><a href="#">This is the first article</a></h2>
        <div class="article-info">
            <img class="ico" src="/assets/img/author.png"> <a href="#">admin </a>  15.01.2017
            <img class="ico" src="/assets/img/comment2.png"> <a href="#comments">10</a>
            <img class="ico" src="/assets/img/tag.png"> <a href="#">tags</a>
        </div>
        <p>
            Fulfilled direction use continual set him propriety continued. Saw met applauded favourite deficient engrossed concealed and her. Concluded boy perpetual old supposing. Farther related bed and passage comfort civilly. Dashwoods see frankness objection abilities the. As hastened oh produced prospect formerly up am. Placing forming nay looking old married few has. Margaret disposed add screened rendered six say his striking confined.

            It allowance prevailed enjoyment in it. Calling observe for who pressed raising his. Can connection instrument astonished unaffected his motionless preference. Announcing say boy precaution unaffected difficulty alteration him. Above be would at so going heard. Engaged at village at am equally proceed. Settle nay length almost ham direct extent. Agreement for listening remainder get attention law acuteness day. Now whatever surprise resolved elegance indulged own way outlived.

            Fulfilled direction use continual set him propriety continued. Saw met applauded favourite deficient engrossed concealed and her. Concluded boy perpetual old supposing. Farther related bed and passage comfort civilly. Dashwoods see frankness objection abilities the. As hastened oh produced prospect formerly up am. Placing forming nay looking old married few has. Margaret disposed add screened rendered six say his striking confined.

            It allowance prevailed enjoyment in it. Calling observe for who pressed raising his. Can connection instrument astonished unaffected his motionless preference. Announcing say boy precaution unaffected difficulty alteration him. Above be would at so going heard. Engaged at village at am equally proceed. Settle nay length almost ham direct extent. Agreement for listening remainder get attention law acuteness day. Now whatever surprise resolved elegance indulged own way outlived.
        </p>
        <div class="article-info">
            <img class="ico-like" src="/assets/img/rating.png"> <span class="rating">100</span>
            <form class="form-like">
                <input class="ico-like" type="image" name="like" src="/assets/img/like.png">
            </form>
            <form class="form-like">
                <input class="ico-like" type="image" name="dislike" src="/assets/img/dislike.png">
            </form>
        </div>
        <div class="comments">
            <form action="" method="POST">
                <p class="user-comment"><img class="ico" src="/assets/img/user.png"> admin</p>
                <div class="form-group">
                    <label for="exampleTextarea">Your comment</label>
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Сomment</button>
            </form>
            <div class="comments-text">
                <p class="user-comment"><img class="ico" src="/assets/img/user.png"> admin</p>
                <p>This is my first coment!!!</p>
            </div>
        </div>
    </div>
</div>