<!-- content arrticle -->
<div class="col-lg-8 mw">
  <div class="article">
    <h2>Add new article</h2>
    <form>
    <div class="form-group">
      <label for="exampleInputEmail1">Title</label>
      <input type="text" name="articleTitle" class="form-control" placeholder="Enter title" required>
    </div>
    <div class="form-group">
      <label for="exampleTextarea">Article</label>
      <textarea class="form-control" name="articleText" rows="15"></textarea>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Tags</label>
      <input type="text" name="articleTags" class="form-control" placeholder="Enter tags" required>
    </div>
    <button type="submit" class="btn btn-primary">Publish</button>
  </form>
  </div>
</div>
