<!-- content arrticle -->
<div class="col-lg-8 mw">
    <div class="community">
        <h2>Create new community</h2>
        <form action="" method="post">
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                <input type="text" name="articleTitle" class="form-control" placeholder="Enter name of community" required>
            </div>
            <div class="form-group">
                <label for="exampleTextarea">Community description and rules</label>
                <textarea class="form-control" name="articleText" rows="15"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>