<!-- content arrticle -->
<div>
    <?php foreach ($this->articles as $article): ?>
        <?php /** @var \MVC\Models\Article $article */ ?>
        <div class="article">
		<h2><a href="/article/<?= $article->getId(); ?>"><?php echo $article->getTitle()?></a></h2>
		<div class="article-info">
			<img class="ico" src="/assets/img/author.png"> <a href="/users/<?= $article->getUser()->getId() ?>"><?php echo $article->getUser()->getNickname();?> </a> <?php echo $article->getCreated() ?>
			<img class="ico" src="/assets/img/comment2.png"> <a href="#comments">10</a>
            <img class="ico" src="/assets/img/tag.png"> <?php foreach (explode(' ', $article->getTags()) as $tagValue): ?><a href="/tags/<?php echo $tagValue?>"><div class="badge badge-default"><?php echo $tagValue?></div></a> <?php endforeach;?>
		</div>
		<p>
            <?php echo $article->getBody()?>
        </>
		<div class="article-info">
			<img class="ico-like" src="/assets/img/rating.png"> <span class="rating"> <?php echo $article->getRating()?></span>
			<form class="form-like">
				<input class="ico-like" type="image" name="like" src="/assets/img/like.png">
			</form>
			<form class="form-like">
				<input class="ico-like" type="image" name="dislike" src="/assets/img/dislike.png">
			</form>
		</div>
		<a class="read-more"  href="/article/<?= $article->getId(); ?>">Read more ...</a>
	</div>
    <?php endforeach;?>
</div>



