<!-- sidebar -->
<div class="col-md-3 ">
    <div class="sidebar bg-primary">
        <div><a href="/"><img src="/assets/img/logo.png" width="100%"></a></div>
        <div id="tabs">
            <ul>
                <li><a href="#tabs-1">Log In</a></li>
                <li><a href="#tabs-2">Register</a></li>
            </ul>
            <div id="tabs-1">
                <form action="/users/json-login" method="post" class="ajax">
                    <div class="form-group">
                        <label for="login_email" class="col-form-label">Email:</label>
                        <input type="text" name="email" class="form-control" autofocus value="<?= $this->email ?>">
                        <span class="error-messages"></span>
                    </div>
                    <div class="form-group">
                        <label for="login_password" class="col-form-label">Password:</label>
                        <input type="password" name="password" class="form-control" >
                        <span class="error-messages"></span>
                    </div>
                    <br/>
                    <div class="text-right">
                        <button class="btn btn-primary">Log In</button>
                    </div>
                </form>
            </div>
            <div id="tabs-2">
                <form action="/users/json-register" method="post" class="ajax">
                    <div class="form-group">
                        <label for="register_username" class="col-form-label">Username:</label>
                        <input type="text" name="username" class="form-control" autofocus >
                        <span class="error-messages"></span>
                    </div>
                    <div>
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="gender" value="male"> Male
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="gender" value="female"> Female
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="register_email" class="col-form-label">Email:</label>
                        <input type="text" name="email" class="form-control" >
                        <span class="error-messages"></span>
                    </div>
                    <div class="form-group">
                        <label for="register_password" class="col-form-label">Password:</label>
                        <input type="password" name="password" class="form-control" >
                        <span class="error-messages"></span>
                    </div>
                    <div class="form-group">
                        <label for="register_repeat_password" class="col-form-label">Repeat Password:</label>
                        <input type="password" name="repeat_password" class="form-control" >
                        <span class="error-messages"></span></div>
                    <br/>
                    <div class="text-right">
                        <button class="btn btn-success" name = "register">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end sidebar -->