<div class="col-md-3">
    <div class="sidebar bg-primary">
        <div><a href="/"><img src="/assets/img/logo.png" width="100%"></a></div>
        <div class="nav nav-pills custom-controls-stacked">
            <ul class="navbar-nav mr-auto">
                <li class="nav-sidebar">
                    <a class="nav-link" href="/article/create">Create article</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link" href="/community/create">Create community</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link" href="#">Settings</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Feed</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Post</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Massage</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Comments</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Saved</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="/users/logout">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</div>