
<div class="col-lg-4 ">
    <div class="sidebar bg-primary">
        SIDEBAR iNFO
        <div class="nav nav-pills custom-controls-stacked">
            <ul class="navbar-nav mr-auto">
                <li class="nav-sidebar">
                    <a class="nav-link" href="#">Rating </a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link" href="#">Subscribers</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link" href="#">Settings</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Feed</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Post</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Massage</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Comments</a>
                </li>
                <li class="nav-sidebar">
                    <a class="nav-link " href="#">Saved</a>
                </li>
            </ul>
        </div>
    </div>
</div>