<div class="row">

    <div class="col-md-6 offset-3">
        <form action="/users/login" method="post">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" name="email" class="form-control" id="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <div class="text-right">
                <button class="btn btn-success">Log in</button>
            </div>
        </form>
    </div>

</div>