
<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card text-center" style="margin: 2%">
            <h3 class="card-header">
                Log In
            </h3>
            <div class="card-block">
                <form action="/users/login" method="post">
                    <div class="form-group">
                        <label for="login_email" class="col-form-label">Email:</label>
                        <input type="email" name="login_email" class="form-control" autofocus required value="<?= $this->email ?>">
                    </div>
                    <div class="form-group">
                        <label for="login_password" class="col-form-label">Password:</label>
                        <input type="password" name="login_password" class="form-control" required>
                    </div>
                    <br/>
                    <div class="text-right">
                        <button class="btn btn-primary">Log In</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>