
<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card text-center" style="margin: 2%">
            <h3 class="card-header">
                User Registration
            </h3>
            <div class="card-block">
                <form action="/users/register" method="post">
                    <div class="form-group">
                        <label for="register_username" class="col-form-label">Username:</label>
                        <input type="text" name="register_username" class="form-control" autofocus required>
                    </div>
                    <div>
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="register_gender" value="male"> Male
                            </label>
                        </div>
                        <div class="form-check form-check-inline">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio" name="register_gender" value="female"> Female
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="register_email" class="col-form-label">Email:</label>
                        <input type="email" name="register_email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="register_password" class="col-form-label">Password:</label>
                        <input type="password" name="register_password" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="register_repeat_password" class="col-form-label">Repeat Password:</label>
                        <input type="password" name="register_repeat_password" class="form-control" required>
                    </div>
                    <br/>
                    <div class="text-right">
                        <button class="btn btn-success" name = "register">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>