<div>
    <div class="article">
        <h2>Add new article</h2>
        <form action="/article/new" method="post" class="ajax">
            <div class="form-group">
                <label for="title">Title</label>
                <input
                        type="text"
                        name="title"
                        class="form-control"
                        placeholder="Enter title"
                        <?php if ($this->article !== null) : ?>
                            value="<?= $this->article->getTitle() ?>"
                        <?php endif; ?>
                >
                <span class="error-messages"></span>
            </div>
            <div class="form-group">
                <label for="body">Article</label>
                <textarea class="form-control" name="body" rows="15"></textarea>
                <span class="error-messages"></span>
            </div>
            <div class="form-group">
                <label for="tags">Tags</label>
                <input type="text" name="tags" class="form-control" placeholder="Enter tags">
                <span class="error-messages"></span>
            </div>
            <div class="form-group">
                <label for="community">Community</label>

                <select name="community" id="community">
                    <option value="-1">None</option>
                    <?php foreach ($this->communities as $community): ?>
                        <?php /** @var \MVC\Models\Community $community */ ?>
                        <option value="<?= $community->getId() ?>"><?= $community->getName() ?></option>
                    <?php endforeach; ?>
                </select>

                <span class="error-messages"></span>
            </div>
            <button type="submit" class="btn btn-primary">Publish</button>
        </form>
    </div>
</div>