<div>
    <div class="article">
        <h2><?= $this->article->getTitle() ?></h2>
        <div class="article-info">
            <img class="ico" src="/assets/img/author.png"> <a href="/users/<?= $this->article->getUser()->getId() ?>"><?php echo $this->article->getUser()->getNickname();?> </a>  <?php echo $this->article->getCreated() ?>
            <img class="ico" src="/assets/img/comment2.png"> <a href="#comments">10</a>
            <img class="ico" src="/assets/img/tag.png"> <a href="#">tags</a>
            <form action="/article/delete" method="post" class="ajax">
                <input type="hidden" name="delete">
                <button class="btn btn-info">delete</button>
            </form>
        </div>
        <p><?= $this->article->getBody(); ?></p>
        <div class="article-info">
            <img class="ico-like" src="/assets/img/rating.png"> <span class="rating">100</span>
            <form class="form-like">
                <input class="ico-like" type="image" name="like" src="/assets/img/like.png">
            </form>
            <form class="form-like">
                <input class="ico-like" type="image" name="dislike" src="/assets/img/dislike.png">
            </form>
         </div>
        <div class="comments">
                <form action="" method="POST">
                <p class="user-comment"><img class="ico" src="/assets/img/user.png"><?= $this->article->getUser()->getNickname() ?></p>
                <div class="form-group">
                    <label for="exampleTextarea">Your comment</label>
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Сomment</button>
            </form>
            <div class="comments-text">
                <p class="user-comment"><img class="ico" src="/assets/img/user.png"> admin</p>
                <p>This is my first coment!!!</p>
            </div>
        </div>
    </div>
</div>