<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <title>Training Pikabu</title>
</head>
<body>
<div class="container-invers bg-primary">

    <?php if (\System\Auth\Session::getInstance()->hasIdentity() === true) : ?>
    <?php include 'menu/user.phtml'; ?>
    <?php else : ?>
    <?php include 'menu/guest.phtml'; ?>
    <?php endif; ?>

</div>
<div class="container content">
    <?= $content; ?>
</div>
<div class="footer bg-primary">
    <p class="project-foter">© project name</p>
</div>
<script src="/assets/js/bootstrap.min.js"></script>
</body>
</html>